vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.splitright=true
vim.opt.splitbelow=true
vim.opt.smartindent=true
vim.opt.termguicolors=true
vim.opt.expandtab = true
vim.opt.tabstop=2
vim.opt.cursorline=true
